"""Added custom email support

Revision ID: 377363986bd0
Revises: 01a88c7a2ac5
Create Date: 2019-02-18 10:27:46.059655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377363986bd0'
down_revision = '01a88c7a2ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuoteRequests', sa.Column('custom_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('QuoteRequests', 'custom_message')
    # ### end Alembic commands ###
