"""Added html support for custom email messages

Revision ID: 822321580562
Revises: 377363986bd0
Create Date: 2019-02-18 13:48:37.297548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822321580562'
down_revision = '377363986bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuoteRequests', sa.Column('custom_message_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('QuoteRequests', 'custom_message_html')
    # ### end Alembic commands ###
